---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 11.0.3-jdk-stretch

inputs:
  - name: tcs-embed-example

run:
  path: tcs-embed-example/ci/build.sh
